name: Hola Mundo

on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
    - name: Hola Mundo
      run: echo "Hola Mundo"

    - name: touch file
      run: touch hola.txt

    - name: Set text
      run: echo "Hola Mundo"  >> hola.txt

    - name: Read text
      run: cat hola.txt


  others:
    runs-on: ubuntu-latest

    steps:
    - name: LS
      run: ls -ltra